train{
    expname = wwbottle
    dataset_class = datasets.PIR.SceneDataset
    model_class = model.implicit_differentiable_renderer.IDRNetwork
    sdf_network = model.implicit_differentiable_renderer.ImplicitNetwork
    color_network = model.polar_render.RenderingNetwork
    loss_class = model.loss.IDRLoss
    learning_rate = 1.0e-4
    learning_rate_cam = 1.0e-4
    num_pixels = 2048
    plot_freq = 10
    alpha_milestones = [250,500,750,1000,1250]
    alpha_factor = 2
    sched_milestones = [2500]
    sched_factor = 0.5
    aolp_render_weight_milestones = [2500]
    stokes_render_weight_milestones = [1000,2500]
    use_refract_ray = True  # 是否使用折线光
    use_color = True
    fused_aolp = True
}
plot{
    plot_nimgs = 1
    max_depth = 3.0
    resolution = 512
}
loss{
    eikonal_weight = 0.1
    mask_weight = 100.0
    aolp_render_weight_init = 0.2
    stokes_render_weight_init = 1
    alpha = 50.0
}
dataset{
    data_dir = ./dtu/wwbottle/
    img_res = [512,612]  # [1028, 1232][1200, 1600][512,612][700,700][1024,1224][512,512]
    num_views = -1
}
model{
    feature_vector_size = 256
    implicit_network
    {
        d_in = 3
        d_out = 1
        dims = [ 512, 512, 512, 512, 512, 512, 512, 512]
        geometric_init = True
        bias = 0.6
        skip_in = [4]
        weight_norm = True
        multires = 6
    }
    refract_ray_tracer
    {
        n_secant_steps = 8
        n_steps = 100
        eta1 = 1.0
        eta2 = 1.52
    }
    straight_ray_tracer
    {
        object_bounding_sphere = 1.0
        sdf_threshold = 5.0e-5
        line_search_step = 0.5
        line_step_iters = 3
        sphere_tracing_iters = 10
        n_steps = 100
        n_secant_steps = 8
    }
    rendering_network
    {
        mode = idr
        d_in = 9
        d_out = 3
        dims = [ 512, 512, 512, 512]
        weight_norm = True
        multires_view = 4
    }
}